styling added
Bearandbird/amber-hinojos-haumea pull request #4
Opened 2024-03-30 17:17 UTC by Bearandbird

2024-03-31 01:03 UTC, toma63 requested changes
Nice design.  It looks like some of the lesson requirements were not met.

These apply to sections, not headings:
 Add spacing (padding/margin) between sections
 Change the alignment of the content of one of your sections
 
  Transform the "Experience" list items into styled blocks
  is calling for the display type to be block

2024-03-31 01:03 UTC, toma63 commented on index.html
>   </style>
Just remove this.

2024-03-31 01:03 UTC, toma63 commented on index.html
> +</head>
Consider adding google fonts as in the extra items for the assignment.

2024-04-02 02:21 UTC, Bearandbird commented
> Nice design. It looks like some of the lesson requirements were not met.
> 
> These apply to sections, not headings: Add spacing (padding/margin) between sections Change the alignment of the content of one of your sections
> 
> Transform the "Experience" list items into styled blocks is calling for the display type to be block

-Thank you- I think it's all fixed now.

2024-04-02 19:21 UTC, merged